version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 1
    commit-message:
      prefix: "chore: "
    allow:
      - dependency-type: "all"
    group:
      group-name: "dependencies"
      group-slug: "weekly"

  - package-ecosystem: "npm"
    directory: "/functions"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 1
    commit-message:
      prefix: "chore(functions): "
    allow:
      - dependency-type: "all"
    group:
      group-name: "functions dependencies"
      group-slug: "weekly"
