version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore: "
    ignore:
      - dependency-name: "eslint"
        versions: ["9.x"]

  - package-ecosystem: "npm"
    directory: "/functions"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore(functions): "
    ignore:
      - dependency-name: "eslint"
        versions: ["9.x"]
