export enum EDriverType {
  SKUS = "SKUS",
  AVERAGE_INVENTORY = "AVERAGE_INVENTORY",
  INVENTORY_VALUE = "INVENTORY_VALUE",
  SHIPPED_CASES = "SHIPPED_CASES",
  INVENTORY_CUBE = "INVENTORY_CUBE",
  SALES = "SALES",
  PLANNERS = "PLANNERS",
  ORDERS = "ORDERS",
  GROSS_MARGIN = "GROSS_MARGIN",
}
