/**
 * Fixed test fixtures used by the cube calculation suite.
 *
 * Shape mirrors what `parseJsonData` produces from an XLSX upload:
 * each row is an object keyed by the COLUMNS header names, in column
 * order. Indices map to those defined in `shared/consts/index.ts`
 * after the db_v3.xlsx schema alignment.
 *
 * Numbers are intentionally tiny and round so assertions in the test
 * file double as documentation of the math.
 */
import { IDataModelCubeRow } from "@shared/models";

/**
 * A 6-row, 2-category cube. Columns appear in the same order as the
 * COLUMNS array so `Object.values(row)[i]` lines up positionally —
 * the contract `getRowValue(row, i)` relies on.
 */
export const sampleCubeRows: IDataModelCubeRow[] = [
  {
    "Codigo Producto": "SKU-1",
    "Categoria de Producto": "A",
    "Sub Categoria de Producto": "A-1",
    "Descripcion del Producto": "Product A1",
    Proveedor: "P1",
    Pais: "CR",
    Empaque: "EA",
    "Cajas por Tarima": 10,
    "Cubicaje por Tarima": 1,
    "Cubicaje Inv Promedio": 5,
    "Mes 1": 0,
    "Mes 2": 0,
    "Mes 3": 0,
    "Mes 4": 0,
    "Mes 5": 0,
    "Mes 6": 0,
    "Mes 7": 0,
    "Mes 8": 0,
    "Mes 9": 0,
    "Mes 10": 0,
    "Mes 11": 0,
    "Mes 12": 0,
    LT1: 0,
    LT2: 0,
    LT3: 0,
    LT4: 0,
    LT5: 0,
    LT6: 0,
    LT7: 0,
    LT8: 0,
    LT9: 0,
    LT10: 0,
    LT11: 0,
    LT12: 0,
    "Bultos Vendidos": 100,
    "Precio Unitario": 10,
    "Costo Unitario": 6,
    "Margen de Utilidad": 0.4,
    "Ventas Totales": 1000,
    "Ventas al Costo": 600,
    "Gross Margin": 400,
    "Inventario Prom Bultos": 50,
    "Inventario Promedio $": 300,
    "Inventario en Transito": 5,
    "Inventario Actual": 60,
    "Bultos Despachados": 95,
    "Nivel de Servicio Actual": 0.95,
  },
  {
    "Codigo Producto": "SKU-2",
    "Categoria de Producto": "A",
    "Sub Categoria de Producto": "A-2",
    "Descripcion del Producto": "Product A2",
    Proveedor: "P1",
    Pais: "CR",
    Empaque: "EA",
    "Cajas por Tarima": 10,
    "Cubicaje por Tarima": 1,
    "Cubicaje Inv Promedio": 5,
    "Mes 1": 0,
    "Mes 2": 0,
    "Mes 3": 0,
    "Mes 4": 0,
    "Mes 5": 0,
    "Mes 6": 0,
    "Mes 7": 0,
    "Mes 8": 0,
    "Mes 9": 0,
    "Mes 10": 0,
    "Mes 11": 0,
    "Mes 12": 0,
    LT1: 0,
    LT2: 0,
    LT3: 0,
    LT4: 0,
    LT5: 0,
    LT6: 0,
    LT7: 0,
    LT8: 0,
    LT9: 0,
    LT10: 0,
    LT11: 0,
    LT12: 0,
    "Bultos Vendidos": 50,
    "Precio Unitario": 20,
    "Costo Unitario": 12,
    "Margen de Utilidad": 0.4,
    "Ventas Totales": 1000,
    "Ventas al Costo": 600,
    "Gross Margin": 400,
    "Inventario Prom Bultos": 25,
    "Inventario Promedio $": 300,
    "Inventario en Transito": 0,
    "Inventario Actual": 30,
    "Bultos Despachados": 45,
    "Nivel de Servicio Actual": 0.9,
  },
  {
    "Codigo Producto": "SKU-3",
    "Categoria de Producto": "B",
    "Sub Categoria de Producto": "B-1",
    "Descripcion del Producto": "Product B1",
    Proveedor: "P2",
    Pais: "CR",
    Empaque: "EA",
    "Cajas por Tarima": 12,
    "Cubicaje por Tarima": 1.5,
    "Cubicaje Inv Promedio": 6,
    "Mes 1": 0,
    "Mes 2": 0,
    "Mes 3": 0,
    "Mes 4": 0,
    "Mes 5": 0,
    "Mes 6": 0,
    "Mes 7": 0,
    "Mes 8": 0,
    "Mes 9": 0,
    "Mes 10": 0,
    "Mes 11": 0,
    "Mes 12": 0,
    LT1: 0,
    LT2: 0,
    LT3: 0,
    LT4: 0,
    LT5: 0,
    LT6: 0,
    LT7: 0,
    LT8: 0,
    LT9: 0,
    LT10: 0,
    LT11: 0,
    LT12: 0,
    "Bultos Vendidos": 200,
    "Precio Unitario": 15,
    "Costo Unitario": 9,
    "Margen de Utilidad": 0.4,
    "Ventas Totales": 3000,
    "Ventas al Costo": 1800,
    "Gross Margin": 1200,
    "Inventario Prom Bultos": 100,
    "Inventario Promedio $": 900,
    "Inventario en Transito": 10,
    "Inventario Actual": 110,
    "Bultos Despachados": 190,
    "Nivel de Servicio Actual": 0.95,
  },
];

/** Parameters sheet — one cost per scorecard category. */
export const sampleParameters = {
  columns: ["name", "label", "type", "subType", "value", "valueType"],
  rows: [
    // STORING costs
    {
      name: "ALMACENAJE_STORAGE",
      label: "Storage",
      type: "almacenaje",
      subType: "costos",
      value: 1000,
      valueType: "amount",
    },
    // STORING investments
    {
      name: "ALMACENAJE_INVESTMENT_BUILDING",
      label: "Building Investment",
      type: "almacenaje",
      subType: "inversiones",
      value: 50000,
      valueType: "amount",
    },
    // INVENTORY costs
    {
      name: "INVENTORY_HANDLING",
      label: "Handling",
      type: "inventario",
      subType: "costos",
      value: 500,
      valueType: "amount",
    },
    // GENERAL financial — investment type used by scorecard
    {
      name: "INV_RATE",
      label: "Investment Rate",
      type: "generales",
      subType: "financieros",
      value: 12,
      valueType: "percentage",
    },
  ],
};
