import {
  EDataModelParameterSubType,
  EDataModelParameterType,
} from "@shared/enums";
import {
  Control,
  FieldErrors,
  useFieldArray,
  UseFormRegister,
} from "react-hook-form";
import { inputField } from "src/utils";
import { InferType } from "yup";

import { parametersScheme } from "../schema";

interface Props {
  register: UseFormRegister<InferType<typeof parametersScheme>>;
  errors: FieldErrors<InferType<typeof parametersScheme>>;
  control: Control<InferType<typeof parametersScheme>>;
  hideAutoGenerated?: boolean;
}

const InventoryParams = ({
  register,
  errors,
  control,
  hideAutoGenerated,
}: Props) => {
  const parametersFieldArray = useFieldArray({
    control,
    name: "parameters",
  });

  return (
    <div className="space-y-4">
      <p className="text-sm text-muted-foreground">Costos</p>
      <div className="space-y-3">
        {parametersFieldArray.fields.map((field, index) =>
          (hideAutoGenerated ? !field.autoCalculated : true) &&
          field.type === EDataModelParameterType.INVENTORY &&
          field.subType === EDataModelParameterSubType.COSTS ? (
            <div key={field.id}>
              {inputField({
                valueType: field.valueType,
                ...register(`parameters.${index}.value` as const, {
                  valueAsNumber: true,
                }),
                label: field.label,
                error: !!errors.parameters?.[index]?.value,
                helperText: errors.parameters?.[index]?.value?.message,
                fullWidth: true,
                disabled: field.autoCalculated,
              })}
            </div>
          ) : null
        )}
      </div>

      <p className="pt-2 text-sm text-muted-foreground">Inversiones</p>
      <div className="space-y-3">
        {parametersFieldArray.fields.map((field, index) =>
          (hideAutoGenerated ? !field.autoCalculated : true) &&
          field.type === EDataModelParameterType.INVENTORY &&
          field.subType === EDataModelParameterSubType.INVESTMENTS ? (
            <div key={field.id}>
              {inputField({
                valueType: field.valueType,
                ...register(`parameters.${index}.value` as const, {
                  valueAsNumber: true,
                }),
                label: field.label,
                error: !!errors.parameters?.[index]?.value,
                helperText: errors.parameters?.[index]?.value?.message,
                fullWidth: true,
                disabled: field.autoCalculated,
              })}
            </div>
          ) : null
        )}
      </div>
    </div>
  );
};

export default InventoryParams;
