name: autoupdate
on:
  push: {}
  merge_group: {}
jobs:
  autoupdate:
    name: autoupdate
    runs-on: ubuntu-22.04
    steps:
      - name: Wait for versioning
        uses: fountainhead/action-wait-for-check@v1.2.0
        id: wait-for-versioning
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          checkName: Versioning
          ref: ${{ github.event.pull_request.head.sha || github.sha }}

      - name: Wait for build to succeed
        if: steps.wait-for-build.outputs.conclusion == 'success'
        uses: fountainhead/action-wait-for-check@v1.2.0
        id: wait-for-build
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          checkName: Build and Deploy
          ref: ${{ github.event.pull_request.head.sha || github.sha }}

      - name: Auto-update
        if: steps.wait-for-build.outputs.conclusion == 'success'
        uses: docker://chinthakagodawita/autoupdate-action:v1
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
