name: Automated Versioning and Release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  versioning:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Configure committer
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - name: Bump version
        uses: qzb/standard-version-action@v1.0.5

      - run: |
          echo "Released version: $VERSION"
        env:
          VERSION: ${{ steps.release.output.version }}
