name: Versioning and Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  versioning:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Configure Git identity
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Determine release type
        id: release_type
        run: |
          if [[ "${{ github.ref_name }}" == "main" ]]; then
            echo "release_type=minor" >> $GITHUB_ENV
          elif [[ "${{ github.head_ref }}" == bugfix/* || "${{ github.head_ref }}" == fix/* ]] || "${{ github.head_ref }}" == hotfix/* ]]; then
            echo "release_type=patch" >> $GITHUB_ENV
          else
            echo "release_type=patch" >> $GITHUB_ENV
          fi

      - name: Bump version
        run: |
          npx standard-version --release-as ${{ env.release_type }} --no-verify
          git push --follow-tags origin main
