name: Automated Versioning and Release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  versioning:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure Git identity
        run: |
          git config user.email "jahume92@gmail.com"
          git config user.name "Jason Hume"

      - name: Bump version
        uses: qzb/standard-version-action@v1.0.5
